/*
 * generated by Xtext
 */
package net.ivoa.vodml.scoping

import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EReference

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class VodslScopeProvider extends AbstractVodslScopeProvider {
    
				override getScope(EObject context, EReference reference) {
					super.getScope(context, reference)
				}
				
}
