/*
 * generated by Xtext 2.9.1
 */
package net.ivoa.vodsl.tests

import com.google.inject.Inject
import net.ivoa.vodsl.vodsl.VoDataModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith

import static org.junit.Assert.*


@RunWith(XtextRunner)
@InjectWith(VodslInjectorProvider)
class VodslValidationTest extends BaseTest {

	@Inject
	ParseHelper<VoDataModel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse(example1)
		assertNotNull(result)
	}

}
