/*
 * generated by Xtext
 */
package net.ivoa.vodml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VodslUiModule extends net.ivoa.vodml.ui.AbstractVodslUiModule {
	public VodslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
