/*
 * generated by Xtext
 */
package net.ivoa.vodml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VodslRuntimeModule extends net.ivoa.vodml.AbstractVodslRuntimeModule {

}
