/*
 * generated by Xtext 2.9.1
 */
package net.ivoa.vodml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VodslStandaloneSetup extends VodslStandaloneSetupGenerated {

	def static void doSetup() {
		new VodslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
