/*
 * generated by Xtext 2.11.0
 */
package net.ivoa.vodsl.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class VodslWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public VodslWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
