/*
 * generated by Xtext 2.9.1
 */
package net.ivoa.vodml.tests

import com.google.inject.Inject
import net.ivoa.vodml.vodsl.VoDataModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(VodslInjectorProvider)
class VodslParsingTest{

	@Inject
	ParseHelper<VoDataModel> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
