/*
 * generated by Xtext 2.9.1
 */
package net.ivoa.vodml.tests

import com.google.inject.Inject
import net.ivoa.vodml.vodsl.VoDataModel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper

import static org.junit.Assert.*
import net.ivoa.vodml.vodsl.VodslPackage

@RunWith(XtextRunner)
@InjectWith(VodslInjectorProvider)
class VodslParsingTest extends BaseTest {

	@Inject
	ParseHelper<VoDataModel> parseHelper;
	@Inject extension ValidationTestHelper

	@Test 
	def void allvalidation() {
		val result = parseHelper.parse(example1) // actually should parse smaller chunk...
		assertNotNull(result)
		
		result.assertWarning(VodslPackage.Literals.MULTIPLICITY,null,"tbd")
	}

}
