/*
 * generated by Xtext
 */
package net.ivoa.vodml.ui.contentassist

import net.ivoa.vodml.ui.contentassist.AbstractVodslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VodslProposalProvider extends AbstractVodslProposalProvider {
}
