#!/usr/bin/env python3
"""Generate a textX grammar (vodsl.tx) from the Xtext source grammar.

Rather than mechanically parsing the Xtext grammar (the two meta-languages
differ substantially), this script writes the textX grammar by hand based
on the Xtext rules, computes a SHA-256 hash of the Xtext source, and
embeds it in the generated file as a change-detection stamp.

Run from the vodsl.python/ directory:
    python generate_grammar.py
"""
from __future__ import annotations

import hashlib
from pathlib import Path

_XTEXT_PATH = Path(__file__).resolve().parent.parent / (
    "net.ivoa.vodsl/src/net/ivoa/vodsl/Vodsl.xtext"
)
_OUTPUT_PATH = (
    Path(__file__).resolve().parent / "src" / "vodsl" / "grammar" / "vodsl.tx"
)

# The textX grammar, written by hand to match the Xtext grammar semantics.
_GRAMMAR_TEMPLATE = """\
// DO NOT EDIT — generated by generate_grammar.py
// Xtext source SHA-256: {xtext_hash}
//
// textX grammar for VODSL, derived from Vodsl.xtext.
// Cross-references are stored as plain QualifiedName strings and resolved
// post-parse in scoping.py.

VoDataModel:
    model=ModelDeclaration
    (includes+=IncludeDeclaration)*
    (elements+=ElementDecl)+
;

ModelDeclaration:
    'model' name=ID '(' version=VERSION ')' description=STRING
    ('author' authors+=STRING)*
    ('title' titular=STRING)?
;

IncludeDeclaration:
    'include' importURI=STRING
;

ElementDecl:
    PackageDeclaration | DefinitionType
;

PackageDeclaration:
    'package' name=ID description=STRING? '{{'
        (elements+=ElementDecl)+
    '}}'
;

DefinitionType:
    ObjectType | DataType | Enumeration | PrimitiveType
;

PrimitiveType:
    (abstract?='abstract')? 'primitive' name=ID
    ('->' superType=QualifiedName)?
    description=STRING
    (constraints+=Constraint)*
;

DataType:
    (pis+=ProcessingInstruction)*
    (abstract?='abstract')? 'dtype' name=ID
    ('->' superType=QualifiedName)?
    (description=STRING)?
    (constraints+=Constraint)*
    '{{'
        (subsets+=SubSet)*
        (content+=AttributeOrReference)*
    '}}'
;

AttributeOrReference:
    Attribute | Reference
;

ObjectType:
    (pis+=ProcessingInstruction)*
    (abstract?='abstract')? 'otype' name=ID
    ('->' superType=QualifiedName)?
    (description=STRING)?
    (constraints+=Constraint)*
    '{{'
        (subsets+=SubSet)*
        (content+=ContentElement)*
    '}}'
;

ContentElement:
    Attribute | Reference | Composition
;

Attribute:
    (pis+=ProcessingInstruction)*
    name=BARE_ID ':' type=QualifiedName (multiplicity=Multiplicity)?
    (key=NaturalKey)? description=STRING
    (semanticConcept=SemanticConcept)?
    (constraints+=Constraint)*
    ';'
;

Composition:
    name=ID ':' type=QualifiedName (multiplicity=Multiplicity)?
    'as' (ordered?='ordered')? 'composition'
    description=STRING
    (semanticConcept=SemanticConcept)?
    (constraints+=Constraint)*
    ';'
;

Reference:
    name=ID (multiplicity=Multiplicity)?
    'references' type=QualifiedName description=STRING ';'
;

Multiplicity:
    '@' ( ('[' minOccurs=INT (',' maxOccurs=SINT)? ']')
        | multiplicitySpec=MultiplicityBound )
;

MultiplicityBound:
    /\\*|\\?|\\+|ONE/
;

Enumeration:
    (abstract?='abstract')? 'enum' name=ID
    ('->' superType=QualifiedName)?
    (description=STRING)?
    (constraints+=Constraint)*
    '{{'
        literals+=EnumLiteral (',' literals+=EnumLiteral)*
    '}}'
;

EnumLiteral:
    name=ID (description=STRING)?
;

Constraint:
    '<' (expr=STRING ('as' language=ConstraintLanguage)?)? '>'
;

ConstraintLanguage:
    /Natural|Regex|OCL/
;

SemanticConcept:
    'semantic' (broadestConcept=STRING)? 'in' vocabularyURI=STRING
;

SubSet:
    'subset' ref=QualifiedName 'as' type=QualifiedName ';'
;

NaturalKey:
    'iskey' ('ofRank' position=INT)?
;

ProcessingInstruction:
    pitext=PI_TEXT
;

// --- Terminal-like rules ---

QualifiedName:
    /(\\^?[A-Za-z_]\\w*:)?\\^?[A-Za-z_]\\w*(\\.\\^?[A-Za-z_]\\w*)*/
;

BARE_ID:
    /\\^?[A-Za-z_]\\w*/
;

VERSION:
    /\\d+(?:\\.\\d+)?/
;

SINT:
    /-?\\d+/
;

PI_TEXT:
    /![^!]*!/
;

Comment:
    /\\/\\/.*?$/  |  /\\/\\*[\\s\\S]*?\\*\\//
;
"""


def generate() -> str:
    """Generate the textX grammar string, stamped with the Xtext hash."""
    xtext_source = _XTEXT_PATH.read_text(encoding="utf-8")
    xtext_hash = hashlib.sha256(xtext_source.encode()).hexdigest()
    return _GRAMMAR_TEMPLATE.format(xtext_hash=xtext_hash)


def main():
    grammar_text = generate()
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(grammar_text, encoding="utf-8")
    print(f"Generated {_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
