/*
 * generated by Xtext 2.11.0
 */
package net.ivoa.vodml.ide

import com.google.inject.Guice
import net.ivoa.vodml.VodslRuntimeModule
import net.ivoa.vodml.VodslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class VodslIdeSetup extends VodslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new VodslRuntimeModule, new VodslIdeModule))
	}
	
}
